In [3]:
!pip install nltk

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

# Create Documents
doc1 = 'Hi, How are you'
doc2 = 'Today is very very pleasant day, and we had lot of fun fun'
doc3 = 'This was amazing experience'
doc_list=[doc1,doc2,doc3]

bagofwords = vectorizer.fit(doc_list)

print(bagofwords)

bagofwords = vectorizer.transform(doc_list)

print(vectorizer.get_feature_names())

print(bagofwords)
print(bagofwords.toarray())


CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)
['amazing', 'and', 'are', 'day', 'experience', 'fun', 'had', 'hi', 'how', 'is', 'lot', 'of', 'pleasant', 'this', 'today', 'very', 'was', 'we', 'you']
  (0, 2)	1
  (0, 7)	1
  (0, 8)	1
  (0, 18)	1
  (1, 1)	1
  (1, 3)	1
  (1, 5)	2
  (1, 6)	1
  (1, 9)	1
  (1, 10)	1
  (1, 11)	1
  (1, 12)	1
  (1, 14)	1
  (1, 15)	2
  (1, 17)	1
  (2, 0)	1
  (2, 4)	1
  (2, 13)	1
  (2, 16)	1
[[0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1]
 [0 1 0 1 0 2 1 0 0 1 1 1 1 0 1 2 0 1 0]
 [1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0]]


In [15]:
#one hot encoding 

from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
myset = set(data)
print("Myset:  " ,myset)
values = array(data)

print("values",values)

# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print("Integer encoding ")
print(integer_encoded)

# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print("one hot encoding ")
print(onehot_encoded)

# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[1, :])])
print(inverted)

Myset:   {'warm', 'cold', 'hot'}
values ['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
Integer encoding 
[0 0 2 0 1 1 2 0 2 1]
one hot encoding 
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
